// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: permission.proto

package permission

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//httpmethod：get，post
//如果不想提供http接口，可以 method:"no"
type HttpMethod int32

const (
	HttpMethod_No   HttpMethod = 0
	HttpMethod_Get  HttpMethod = 1
	HttpMethod_Post HttpMethod = 2
)

var HttpMethod_name = map[int32]string{
	0: "No",
	1: "Get",
	2: "Post",
}

var HttpMethod_value = map[string]int32{
	"No":   0,
	"Get":  1,
	"Post": 2,
}

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return proto.EnumName(HttpMethod_name, int32(x))
}

func (x *HttpMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HttpMethod_value, data, "HttpMethod")
	if err != nil {
		return err
	}
	*x = HttpMethod(value)
	return nil
}

func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

type Permission int32

const (
	Permission_IgnoreLogin           Permission = 2
	Permission_LoginWithNoPermission Permission = 1
	Permission_NeedPerm              Permission = 0
)

var Permission_name = map[int32]string{
	2: "IgnoreLogin",
	1: "LoginWithNoPermission",
	0: "NeedPerm",
}

var Permission_value = map[string]int32{
	"IgnoreLogin":           2,
	"LoginWithNoPermission": 1,
	"NeedPerm":              0,
}

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return proto.EnumName(Permission_name, int32(x))
}

func (x *Permission) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Permission_value, data, "Permission")
	if err != nil {
		return err
	}
	*x = Permission(value)
	return nil
}

func (Permission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{1}
}

type HttpRule struct {
	Method *HttpMethod `protobuf:"varint,1,req,name=method,enum=bidewu.HttpMethod" json:"method,omitempty"`
	//权限
	Perm                 *Permission `protobuf:"varint,2,req,name=perm,enum=bidewu.Permission,def=0" json:"perm,omitempty"`
	Permcode             *string     `protobuf:"bytes,3,opt,name=permcode" json:"permcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HttpRule) Reset()         { *m = HttpRule{} }
func (m *HttpRule) String() string { return proto.CompactTextString(m) }
func (*HttpRule) ProtoMessage()    {}
func (*HttpRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}
func (m *HttpRule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HttpRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HttpRule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HttpRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRule.Merge(m, src)
}
func (m *HttpRule) XXX_Size() int {
	return m.Size()
}
func (m *HttpRule) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRule.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRule proto.InternalMessageInfo

const Default_HttpRule_Perm Permission = Permission_NeedPerm

func (m *HttpRule) GetMethod() HttpMethod {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return HttpMethod_No
}

func (m *HttpRule) GetPerm() Permission {
	if m != nil && m.Perm != nil {
		return *m.Perm
	}
	return Default_HttpRule_Perm
}

func (m *HttpRule) GetPermcode() string {
	if m != nil && m.Permcode != nil {
		return *m.Permcode
	}
	return ""
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*HttpRule)(nil),
	Field:         72295628,
	Name:          "bidewu.http",
	Tag:           "bytes,72295628,opt,name=http",
	Filename:      "permission.proto",
}

func init() {
	proto.RegisterEnum("bidewu.HttpMethod", HttpMethod_name, HttpMethod_value)
	proto.RegisterEnum("bidewu.Permission", Permission_name, Permission_value)
	proto.RegisterType((*HttpRule)(nil), "bidewu.HttpRule")
	proto.RegisterExtension(E_Http)
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_c837ef01cbda0ad8) }

var fileDescriptor_c837ef01cbda0ad8 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x3b, 0x69, 0xe9, 0x9f, 0xff, 0x56, 0xec, 0x30, 0x50, 0x88, 0x5d, 0x84, 0xd0, 0x8d,
	0xa5, 0x8b, 0x54, 0xba, 0xac, 0x2b, 0x83, 0xda, 0x16, 0xb4, 0x96, 0x60, 0x29, 0xba, 0xb3, 0xcd,
	0x98, 0x0c, 0xb4, 0xb9, 0x21, 0x99, 0xe0, 0x0b, 0xf8, 0x10, 0xae, 0x7d, 0x0e, 0x1f, 0x40, 0xc1,
	0x85, 0x8f, 0x20, 0xf5, 0x45, 0x24, 0x89, 0xcd, 0xe8, 0x6a, 0xee, 0x99, 0xf9, 0xb8, 0xe7, 0x70,
	0x06, 0x68, 0xc4, 0xe3, 0x8d, 0x48, 0x12, 0x81, 0xa1, 0x1d, 0xc5, 0x28, 0x91, 0xd5, 0x97, 0xc2,
	0xe3, 0x0f, 0x69, 0xdb, 0xf2, 0x11, 0xfd, 0x35, 0xef, 0xe7, 0xb7, 0xcb, 0xf4, 0xbe, 0xef, 0xf1,
	0x64, 0x15, 0x8b, 0x48, 0x62, 0x5c, 0x90, 0x9d, 0x47, 0x02, 0xfa, 0x58, 0xca, 0xc8, 0x4d, 0xd7,
	0x9c, 0xf5, 0xa0, 0xbe, 0xe1, 0x32, 0x40, 0xcf, 0x20, 0x96, 0xd6, 0xdd, 0x1f, 0x30, 0xbb, 0xd8,
	0x63, 0x67, 0xc4, 0x65, 0xfe, 0xe2, 0xfe, 0x10, 0xec, 0x08, 0x6a, 0x99, 0xad, 0xa1, 0xfd, 0x25,
	0x67, 0x65, 0x94, 0xa1, 0x3e, 0xe5, 0xdc, 0xcb, 0xb4, 0x9b, 0x93, 0xac, 0x0d, 0x7a, 0x76, 0xae,
	0xd0, 0xe3, 0x46, 0xd5, 0x22, 0xdd, 0xff, 0x6e, 0xa9, 0x7b, 0x87, 0x00, 0xca, 0x83, 0xd5, 0x41,
	0x9b, 0x22, 0xad, 0xb0, 0x7f, 0x50, 0x1d, 0x71, 0x49, 0x09, 0xd3, 0xa1, 0x36, 0xc3, 0x44, 0x52,
	0xad, 0x77, 0x0e, 0xa0, 0x2c, 0x58, 0x13, 0x1a, 0x13, 0x3f, 0xc4, 0x98, 0x5f, 0xa0, 0x2f, 0x42,
	0xaa, 0xb1, 0x03, 0x68, 0xe5, 0xe3, 0x42, 0xc8, 0x60, 0x8a, 0x8a, 0xa4, 0x84, 0xed, 0x41, 0x19,
	0x88, 0x56, 0x86, 0x23, 0xa8, 0x05, 0x52, 0x46, 0xcc, 0xb4, 0x8b, 0x8a, 0xec, 0x5d, 0x45, 0x76,
	0x91, 0xe1, 0x2a, 0x92, 0x02, 0xc3, 0xc4, 0x78, 0x7f, 0x7b, 0xe9, 0x58, 0xa4, 0xdb, 0x18, 0xd0,
	0xdf, 0x5d, 0x64, 0x6d, 0xb9, 0xf9, 0x02, 0xe7, 0xe6, 0x75, 0x6b, 0x92, 0x8f, 0xad, 0x49, 0x3e,
	0xb7, 0x26, 0x79, 0xfa, 0x32, 0x2b, 0xd0, 0x5c, 0xe1, 0x66, 0x07, 0xdf, 0xa5, 0x32, 0x70, 0xa8,
	0x93, 0x0b, 0x95, 0x66, 0x46, 0x6e, 0x5b, 0xea, 0xcf, 0x8e, 0xd5, 0xf8, 0xac, 0x81, 0x33, 0x39,
	0x3d, 0x5b, 0xcc, 0x4f, 0xe6, 0xd7, 0xe3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x60, 0x2b,
	0xdf, 0xd8, 0x01, 0x00, 0x00,
}

func (m *HttpRule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpRule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HttpRule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Permcode != nil {
		i -= len(*m.Permcode)
		copy(dAtA[i:], *m.Permcode)
		i = encodeVarintPermission(dAtA, i, uint64(len(*m.Permcode)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Perm == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintPermission(dAtA, i, uint64(*m.Perm))
		i--
		dAtA[i] = 0x10
	}
	if m.Method == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintPermission(dAtA, i, uint64(*m.Method))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPermission(dAtA []byte, offset int, v uint64) int {
	offset -= sovPermission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HttpRule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Method != nil {
		n += 1 + sovPermission(uint64(*m.Method))
	}
	if m.Perm != nil {
		n += 1 + sovPermission(uint64(*m.Perm))
	}
	if m.Permcode != nil {
		l = len(*m.Permcode)
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPermission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPermission(x uint64) (n int) {
	return sovPermission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HttpRule) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HttpRule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HttpRule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var v HttpMethod
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= HttpMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Method = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Perm", wireType)
			}
			var v Permission
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= Permission(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Perm = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permcode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Permcode = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPermission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPermission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPermission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPermission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPermission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPermission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPermission = fmt.Errorf("proto: unexpected end of group")
)
